//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCardPlease.Desktop.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreditCardPlease.Desktop.Resources.Localization.Strings - Copy", typeof(Strings___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string CardFormCancel {
            get {
                return ResourceManager.GetString("CardFormCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número do Cartão.
        /// </summary>
        internal static string CardFormCardNumber {
            get {
                return ResourceManager.GetString("CardFormCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Validade.
        /// </summary>
        internal static string CardFormExpirationDate {
            get {
                return ResourceManager.GetString("CardFormExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos Obrigatórios.
        /// </summary>
        internal static string CardFormRequiredFields {
            get {
                return ResourceManager.GetString("CardFormRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de Segurança.
        /// </summary>
        internal static string CardFormSecurityCode {
            get {
                return ResourceManager.GetString("CardFormSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Dados.
        /// </summary>
        internal static string CardFormSendData {
            get {
                return ResourceManager.GetString("CardFormSendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O-Obrigada!.
        /// </summary>
        internal static string CardFormThanks {
            get {
                return ResourceManager.GetString("CardFormThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O-olá!
        ///V-Você poderia fornecer seus
        ///dados do cartão de crédito, porfavorzinho?.
        /// </summary>
        internal static string CardFormTitle {
            get {
                return ResourceManager.GetString("CardFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-eu preciso desses dados... Por favor....
        /// </summary>
        internal static string CreditCardWindowTitle {
            get {
                return ResourceManager.GetString("CreditCardWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V-Você realmente quer limpar os dados do cartão?!
        ///
        ///P-Por favor, não faça nada estúpido!.
        /// </summary>
        internal static string DialogCancelDescription {
            get {
                return ResourceManager.GetString("DialogCancelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ufa!! Você me assustou...
        /// </summary>
        internal static string DialogCancelNoDescription {
            get {
                return ResourceManager.GetString("DialogCancelNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mds...
        /// </summary>
        internal static string DialogCancelNoTitle {
            get {
                return ResourceManager.GetString("DialogCancelNoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-Tem certeza?....
        /// </summary>
        internal static string DialogCancelTitle {
            get {
                return ResourceManager.GetString("DialogCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por que você faria isso? 🥺.
        /// </summary>
        internal static string DialogCancelYesDescription {
            get {
                return ResourceManager.GetString("DialogCancelYesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :( O que você fez?....
        /// </summary>
        internal static string DialogCancelYesTitle {
            get {
                return ResourceManager.GetString("DialogCancelYesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M-Muito obrigada! &gt;\\\\~\\\\&lt;
        ///
        ///Seus dados do cartão de crédito estão em boas mãos! ❤️.
        /// </summary>
        internal static string DialogSendDescription {
            get {
                return ResourceManager.GetString("DialogSendDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eu não posso crer que você realmente fez isso!.
        /// </summary>
        internal static string DialogSendTitle {
            get {
                return ResourceManager.GetString("DialogSendTitle", resourceCulture);
            }
        }
    }
}
