//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCardPlease.Desktop.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreditCardPlease.Desktop.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CardFormCancel {
            get {
                return ResourceManager.GetString("CardFormCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string CardFormCardNumber {
            get {
                return ResourceManager.GetString("CardFormCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        internal static string CardFormExpirationDate {
            get {
                return ResourceManager.GetString("CardFormExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Fields.
        /// </summary>
        internal static string CardFormRequiredFields {
            get {
                return ResourceManager.GetString("CardFormRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Code.
        /// </summary>
        internal static string CardFormSecurityCode {
            get {
                return ResourceManager.GetString("CardFormSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Data.
        /// </summary>
        internal static string CardFormSendData {
            get {
                return ResourceManager.GetString("CardFormSendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-Thanks!.
        /// </summary>
        internal static string CardFormThanks {
            get {
                return ResourceManager.GetString("CardFormThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H-Hello!
        ///C-Could you provide your
        ///credit card info, pretty please?.
        /// </summary>
        internal static string CardFormTitle {
            get {
                return ResourceManager.GetString("CardFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I-I need that data... Please....
        /// </summary>
        internal static string CreditCardWindowTitle {
            get {
                return ResourceManager.GetString("CreditCardWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-You really want to clear the card data?!
        ///
        ///P-please don&apos;t do anything stupid!.
        /// </summary>
        internal static string DialogCancelDescription {
            get {
                return ResourceManager.GetString("DialogCancelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phew!! You scared me...
        /// </summary>
        internal static string DialogCancelNoDescription {
            get {
                return ResourceManager.GetString("DialogCancelNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omg...
        /// </summary>
        internal static string DialogCancelNoTitle {
            get {
                return ResourceManager.GetString("DialogCancelNoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-are you sure?....
        /// </summary>
        internal static string DialogCancelTitle {
            get {
                return ResourceManager.GetString("DialogCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why would you do that? 🥺.
        /// </summary>
        internal static string DialogCancelYesDescription {
            get {
                return ResourceManager.GetString("DialogCancelYesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :( What you&apos;ve done?....
        /// </summary>
        internal static string DialogCancelYesTitle {
            get {
                return ResourceManager.GetString("DialogCancelYesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-Thank you so much! &gt;\\\\~\\\\&lt;
        ///
        ///Your credit card data is in good hands! ❤️.
        /// </summary>
        internal static string DialogSendDescription {
            get {
                return ResourceManager.GetString("DialogSendDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t believe you really did that!.
        /// </summary>
        internal static string DialogSendTitle {
            get {
                return ResourceManager.GetString("DialogSendTitle", resourceCulture);
            }
        }
    }
}
